### ISSUE TITLE
Error estimating pairwise distances from the full tree

### ISSUE THREAD

**Issue by jpwrobinson** [jonchang/fishtree#10]
I want to estimate phylogenetic distances for species not included in the tree of life, and doing this by estimating the average family-level distance of missing species to all other species. 

I'd like to use the full tree phylogeny to do this, but run into the following `ape` error:

```
## get entire tree of life, first tree
full_phy <- fishtree_complete_phylogeny()[[1]] 

## estimate pairwise distances
full_dist <- cophenetic.phylo(full_phy)

Error in double(nm * nm) : vector size cannot be NA
In addition: Warning message:
In nm * nm : NAs produced by integer overflow
```

Is this a known bug?

**Comment by jonchang** [comment]
The problem is that the full phylogeny is too large for whatever method ape uses to compute cophenetic distances.  You can see similar behavior if you just run `x <- rtree(30000); cophenetic(x)`

The "bug" is with fishes for having just too many darn species 🙂

**Comment by jonchang** [comment]
Thinking about how to solve your problem: it should be sufficient to break the phylogeny into subtrees of at most ~10000 species, then computing the cophenetic distance both between and within those chunks. Within a subtrees, you can use the distance values as usual. Between subtrees, you can just use the distance from one subtrees to the other. Because the phylogeny is ultrametric, the identity of the specific tip shouldn't matter when comparing across disconnected subtrees.

**Comment by jpwrobinson** [comment]
Ah that makes sense, thanks for the super quick reply Jon.

I was wondering if subtrees are equivalent to the full tree, or other subtrees - perfect. So a family-level distance would be:

within its subtree - the average distance to other species
to different subtrees - the distance between subtrees + species' distances within other subtrees

Can I estimate 'between subtree' distances with `cophenetic`?

**Comment by jonchang** [comment]
>  to different subtrees - the distance between subtrees + species' distances within other subtrees

If you collapse the full tree into just exemplars of what the subtrees represent, this is actually just the distance between subtrees, since the phylogeny is ultrametric.

![image](https://user-images.githubusercontent.com/213484/97561067-b3600200-1a33-11eb-9cf2-2ed39194d37b.png)

If for example our two subtrees are t1 + t5 and t2 + t3 + t4, the distance between t1 and t2 is the same as the distance between t1 and t3. You can take advantage of this when working with a large phylogeny like the complete fish tree.
